services:
  - type: web
    name: insara-chatbot-api
    runtime: python
    rootDir: chatbot-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
